// Generated Mar 26, 2018 7:41:31 AM by Hibernate Tools 5.2.8.Final
package com.cdc.mitrais.model;

/**
 * Articles generated by hbm2java
 */

public class Article implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer articleId;
	private String title;
	private String category;

	public Article() {
	}

	public Article(String title, String category) {
		this.title = title;
		this.category = category;
	}

	
	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
