package com.cdc.mitrais.model;

/**
 * Customer generated by hbm2java
 */

public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String lname;
	private String fname;
	private Integer age;
	private String sex;
	private String married;
	private Integer children;
	private String smoker;

	public Customer() {
	}

	public Customer(String lname) {
		this.lname = lname;
	}

	public Customer(String lname, String fname, Integer age, String sex, String married, Integer children,
			String smoker) {
		this.lname = lname;
		this.fname = fname;
		this.age = age;
		this.sex = sex;
		this.married = married;
		this.children = children;
		this.smoker = smoker;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	
	public String getMarried() {
		return this.married;
	}

	public void setMarried(String married) {
		this.married = married;
	}

	
	public Integer getChildren() {
		return this.children;
	}

	public void setChildren(Integer children) {
		this.children = children;
	}

	
	public String getSmoker() {
		return this.smoker;
	}

	public void setSmoker(String smoker) {
		this.smoker = smoker;
	}

}
